import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import S from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={S.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={S.main}>
        <h1 className={S.title}>
         Multi project Frontend Mentor
        </h1>

        <section>
          <Link href="/card">
            <a>Product card</a>
          </Link>
        </section>

        
      </main>

  
    </div>
  )
}

export default Home
